sudo: required
dist: trusty
language: python

python:
 - 2.7

env:
  matrix:
   - DJANGO_VERSION=1.9.13
#   - DJANGO_VERSION=1.10.7
#   - DJANGO_VERSION=1.11.2

install:
 - sudo apt-get update
 - ./install.sh
 - ./env/bin/pip install -U django==$DJANGO_VERSION
 - ./env/bin/pip install coverage
 - ./env/bin/pip install -e git://github.com/LePetitTim/django-paperclip.git@Django_110#egg=django-paperclip
 
 - pip install flake8==3.5.0

before_script:
 - flake8
 - ./env/bin/pip freeze

script:
 - ./env/bin/python ./manage.py test
 - ./env/bin/coverage run --include="mapentity/*" manage.py test

after_success:
 - pip install coveralls
 - coveralls
