sudo: required
dist: trusty
language: python

python:
 - 2.7

env:
  global:
   - CPLUS_INCLUDE_PATH=/usr/include/gdal
   - C_INCLUDE_PATH=/usr/include/gdal
  matrix:

  - DJANGO_VERSION=1.10.7

install:
 - sudo apt-get update
 - sudo apt-get install -y libgdal1-dev libproj-dev libgeos-dev libspatialite-dev
 - pip install -U setuptools
 - pip install git+git://github.com/tinio/pysqlite.git@extension-enabled#egg=pysqlite

   # This is a dependency of our Django quicktest script
 - pip install argparse

 - pip install gdal==1.10.0
 - pip install -e git://github.com/LePetitTim/django-paperclip.git@Django_110
 - pip install html5lib==0.999
 - pip install -r requirements.txt
 - pip install -U django==$DJANGO_VERSION

 - pip install coverage

 - pip install flake8==3.5.0

 - python setup.py develop

before_script:
 - flake8
 - pip freeze

script:
 - ./manage.py test
 - coverage run --include="mapentity/*" ./manage.py test

after_success:
 - pip install coveralls
 - coveralls
